#! /usr/bin/env bash
#######################################################################
# gpg_verify_uids - GPG Keysigning Party E-mail Address Verification  #
#######################################################################
# See the accompanying file README.md for a full description of the
# reason to use this script, and the options and parameters.
#---------------------------------------------------------------------
# Given a GPG key ID on the command line, fetches that key from a
# public keyserver; creates a subdirectory under the working directory
# (defaults to $HOME/gpg_keysigning_work) for that key ID. Writes a
# writes a copy of the fetched public key and a copy of key, cleaned.
# Generates a random nonce string for each UID in the key, formats an
# email message with the nonce and some other personalization. Signs
# and encrypts the message with the target key. Saves a copy of each
# message in the clear and signed/encrypted. Sends out the email,
# optionally.
#----------------------------------------------------------------------
# Copyright (C) 2013  Robert B. Jenson  <rbj_gpg@spotch.com>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License along
#   with this program; if not, write to the Free Software Foundation, Inc.,
#   51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
#######################################################################

#######################################################################
# CONFIGURATION PARAMETERS
#######################################################################

#  Top level directory. Work on each key goes in a sub-directory
#  under here, named by the full keyid. Will be created if it
#  doesn't exist. If you want to use an alternate keyring for keysigning,
#  this would be a good place to put it.
WORKING_DIR="${HOME}/gpg_keysigning_work"

# How long (in bytes of random data) do you want your nonce to be?
# The openssl command must be in your path
RANDBYTES=20

# Set this value to 1 if you want the script to send out the emails directly, or
# call with the "-s" or "--send-mail" command-line switch.
# The files will be saved in the working directory in all cases. Defaults to not
# sending email messages.
export DO_MAIL=0

# Set value of DEBUG > 0 to output debugging messages. The higher the level
#  the more verbose this script will be. I think the highest level we used
#  is 3. Set this value to the initial debugging level. Value on the command line
#  will then change this.
export DEBUG=0

# If you are having problems with GPG you can bump up the verbosity here
export VERBOSITY=""
# Uncomment if you want GPG to be more verbose:
#VERBOSITY="-v"
#VERBOSITY="-v -v"

GPGDEBUG="--debug-level=none"
# Uncomment if you want debugging output. Level can be basic, advanced, expert or guru
#GPGDEBUG="--debug-level=basic"

# Set ALTKEYRINGS to 1 if you want to use a keyring other than your default keyring.
# If you do use an alternate keyring, it is up to you to copy it to the working
# directory, or point to the location. If you set this to 1, you must point to
# the secret keyring and trustdb too.
ALTKEYRINGS=0

if [ $ALTKEYRINGS -gt 0 ]
then
# Important assumption here -- you have created these keyrings #
# and they contain your public and secret keys in them!!!      #
    PUBRING="${WORKING_DIR}/pubring.gpg"
    SECRING="${WORKING_DIR}/secring.gpg"
    TRUSTDB="${WORKING_DIR}/trustdb.gpg"
fi    

###############################################################################
# The mail message template. Edit this as you see fit. Names surrounded by %% #
# will get substituted later. If you want to have an external template file   #
# you can twiddle this function to cat it.                                    #
###############################################################################

mail_template () {

cat - <<EOF
Dear %%FIRSTNAME%%,

    Thank you for participating in the Keysigning Party, and agreeing
    to exchange key signatures with me.

    This is message %%COUNTER%% of up to %%TOTALMSGS%% that I will be
    sending to you. This is part of my process for signing PGP/GPG
    keys. I have verified your identity in person, but I would like to
    verify that the email addresses in the key UID packets belong to
    the person who controls the key that I'm signing (presumably, that
    is you).

    I am sending one message to each email address in a PGP/GPG UID
    string of your PGP/GPG key 0x%%KEYID%%. Each email message is
    encrypted with your public key, and it contains a "nonce" string,
    of ${RANDBYTES} randomly-generated bytes (ASCII-armored).

    Your nonce is: %%NONCE%%     %%EMAIL%%

    Please send a reply to me at either of my email addresses,
    encrypted with my public key (available from any keyserver,
    details below). Your reply should include the nonce from above.

    If your key has multiple UIDs, you will receive multiple messages
    like this, each with a different nonce. You may return all the
    nonces in one encrypted email message. Your knowledge of the nonce
    is sufficient to connect the key to your email address.

    If I am signing multiple keys for you, I might only send you one
    nonce per distinct email address.

    Let me know if you have any questions about this.


Best regards,

_rob_

EOF
}

GPGOPTS="${VERBOSITY} ${GPGDEBUG} --armor"

if [ $ALTKEYRINGS -gt 0 ]
then
    GPGOPTS="${GPGOPTS} --no-default-keyring --keyring ${PUBRING} \
	--secret-keyring ${SECRING} \
	--trustdb ${TRUSTDB}"
fi

# Set these if the commands are not in your path or you would prefer
# to set the path for them
GPGCMD=
MAILCMD=

#############################################
###### NO MORE CONFIGURATION BELOW HERE #####
#############################################

####################################
# Clean up if something goes wrong #
####################################

cleanup () {
    cd ${STARTDIR}
}

################################################
# Exit with error messages and a return value  #
################################################

errorexit () {
    retval=$1
    shift
    while [ $# -gt 0 ]
    do
	echo $1
	shift
    done	

    cleanup
    
    exit $retval
}
    
##########################################################################
# Output debugging messages to stderr if the value of $DEBUG is greater  #
# than or equal to the level of the message (parameter 1).               #
##########################################################################

debugmsg () {
    debuglevel=$1

    if [ $debuglevel ]; then shift; else return 0; fi

    if [ $DEBUG -ge ${debuglevel} ]
    then
	while [ $# -gt 0 ]
	do
	    echo "$1" >&2
	    shift
	done
    fi
}

##########################################################
# Print out help message for using the program and exit. #
##########################################################

helpmsg () {
    echo "${PROGNAME} [-h|--help] [-v|--verbose] [-d|--debug <debuglvl>] [-s|--send-email] <keyid>"
    echo ""
    echo "Generates messages to each UID on the key with a random nonce"
    echo "-h or --help displays this help message"
    echo "-d or --debug followed by an integer sets debug level"
    echo "-s or --send-email sends the emails. Emails will be saved to ${WORKING_DIR}/${keyid}"
    echo "keyid must be a 16-hex digit PGP key ID"
}

##########################################################
# Parse the arguments on the command line                #
##########################################################

parse_commandline () {

    while [ $# -gt 1 ]
    do
	debugmsg 3 "parse_commandline: Top of loop $# -> $1"
	
	case $1 in
	    -d | --debug )
		export DEBUG=$2
		shift
		;;

	    -h | --help )
		helpmsg
		exit 0
		;;

	    -s | --send-mail )
		export DO_MAIL=1
		;;

	    -v | --verbose )
		export VERBOSITY="${VERBOSITY} --verbose"
		;;
		
	esac

	shift
    done

    lastparam=$1

    if [[ ${lastparam} =~ ^(-h|--help)$ ]]
    then
	helpmsg
	exit 0
    fi

    if [[ ${lastparam} =~ [0-9A-F]{16} ]]
    then
	export KEYID="${lastparam}"
    else
	if [[ ${lastparam} =~ ^Ox[0-9a-fA-F]{16}$ ]]
	then
	  export KEYID=${lastparam:2}
	else
	    helpmsg
	    exit 1
	fi
    fi	
}

##########################################################
# Generate a number of random bytes and return an ASCII- #
# armored string.                                        #
##########################################################

gen_random () {

    bytecount=${1}
    if [ ! ${bytecount} ]; then bytecount=${RANDBYTES}; fi
    if [ ${bytecount} -le 0 ]; then return 2; fi

    nonce=`${GPGCMD} --gen-random --armor 2 ${bytecount}`

    echo "$nonce"
    return 0
}

###############################################
# Validate that the working directory and key #
# directory exist. Create them if necessary.  #
###############################################
setup_key_directory () {

    directory=$1
    debugmsg 3 "setup_working_directory: Called with directory=$1"

    error=`mkdir -m 700 -p ${directory} 2>&1`
    if [ $? -ne 0 ]
    then
	if echo error | egrep -v "File exists"
	then
	    errorexit 1 "Could not create ${directory}"
	fi
    fi    
}


##########################################################################
# MAIN PROGRAM BEGINS HERE
##########################################################################

trap 'cleanup; exit 17'  2 3 5 10 13 15

export PROGNAME=`basename $0`

parse_commandline $*

GPGCMD=${GPGCMD:-`which gpg`}
if [ X$GPGCMD = X ]; then errorexit 1 "No GPG command found"; fi

MAILCMD=${MAILCMD:-`which mailx`}
if [ $DO_MAIL -gt 0 ]
then
    if [ X$MAILCMD = X ]; then errorexit 1 "No MAIL command found"; fi
else
    MAILCMD="echo"
fi

STARTDIR=`pwd`

KEYDIR="${WORKING_DIR}/${KEYID}"

setup_key_directory ${KEYDIR}

cd ${KEYDIR}

# See if we can fetch the key
debugmsg 3 "Fetching GPG Key $KEYID"
$GPGCMD $GPGOPTS --recv-key $KEYID
if [ $? -ne 0 ]
then
    errorexit 2 "No key for $KEYID available from keyserver"
fi    

$GPGCMD $GPGOPTS --export $KEYID > ${KEYID}_fromkeyserver.asc

$GPGCMD $GPGOPTS --export-options export-clean --export $KEYID > ${KEYID}_cleaned.asc

UIDFILE="${KEYID}_uids"
$GPGCMD $GPGOPTS --list-key --with-colons $KEYID | awk -F: '/^uid/ {print($10)}' > ${UIDFILE}

TOTALMSGS=`wc -l ${UIDFILE} | awk '{print($1)}'`
debugmsg 2 "${TOTALMSGS} user ids found."

if [ $TOTALMSGS -le 0 ]; then errorexit 2 "No UIDs found in key $KEYID"; fi

# Generate a manifest file to be merged later into the tracking database
# You can use the MANIFEST file to verify the nonce when you get your responses
MANIFEST="${KEYID}_manifest"
COUNTER=1

if [ ! -f ${MANIFEST} ]; then > $MANIFEST; fi

cat ${UIDFILE} | while read LINE
do
    # Assume that their first name is the first token in the UID. This is probably wrong in some
    # countries and weird UID formats
    FIRSTNAME=`echo $LINE | awk -F\  '{print($1)}'`

    # Also assume that the email address is enclosed in < > brackets
    EMAIL=`echo $LINE | sed 's/^.*<\(.*@.*\)>.*$/\1/'`
    if [ X$EMAIL = X ]
    then
	debugmsg 0 "Unable to extract email address from: $LINE ... skipping"
	TOTALMSGS=`expr $TOTALMSGS - 1`
	continue
    fi

    debugmsg 1 "Extracted email address ${EMAIL} from UID"

    NONCE=`gen_random ${RANDBYTES}`

    debugmsg 2 "Created nonce: ${NONCE}"

    echo "${KEYID}|${COUNTER}|${LINE}|${NONCE}|${EMAIL}|${FIRSTNAME}" >> $MANIFEST

    FILENAME=`echo "nonce_to_send_to_${EMAIL}.${COUNTER}.txt" | sed 's/@/_at_/'`

    debugmsg 1 "Unencrypted message file: ${FILENAME}"

    mail_template | sed \
	-e 's^%%FIRSTNAME%%^'$FIRSTNAME'^' \
	-e 's^%%COUNTER%%^'$COUNTER'^' \
	-e 's^%%TOTALMSGS%%^'$TOTALMSGS'^' \
	-e 's^%%KEYID%%^'$KEYID'^' \
	-e 's^%%NONCE%%^'$NONCE'^' \
	-e 's^%%EMAIL%%^'$EMAIL'^' > ${FILENAME}

    $GPGCMD $GPGOPTS --encrypt --sign --recipient ${KEYID} ${FILENAME}

    if [ -f ${FILENAME}.asc ]
    then
	if [ $DO_MAIL -gt 0 ]
	then
	    command="${MAILCMD} -s \"GPG Keysigning Mail Verification Message ${COUNTER}\" \
		${EMAIL} \< ${FILENAME}.asc"

	    debugmsg 2 "Executing command" "${command}"

	    ${command}
	fi
    else
    	echo "Error: Did not find file ${FILENAME}.asc ... not attempting to mail it"
    fi

    COUNTER=`expr 1 + $COUNTER`
done    

cleanup

